version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beer_django_api
    volumes:
      - ./src:/src
    ports:
      - 8000:8000
    env_file:
      - db_keys_for_sand.txt
    #    depends_on:
    #      - db
    #    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    command: bash -c "gunicorn -w 2 src.wsgi:application -b 0.0.0.0:8000"
